name: Create Release
run-name: Create Release v${{ github.event.inputs.version }}

on:
    workflow_dispatch:
        inputs:
            version:
                description: "The version to release (e.g., 1.2.3). The 'v' prefix is added automatically."
                required: true

permissions:
    contents: write

jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
              with:
                  fetch-depth: 0

            - name: Npm setup
              uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
              with:
                  node-version: 24.12.0
                  cache: "npm"

            - name: Update package.json version
              run: npm version --new-version ${{ github.event.inputs.version }} --no-git-tag-version

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build action
              run: npm run build

            - name: Commit changes
              uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
              with:
                  commit_message: "ðŸ”– Release v${{ github.event.inputs.version }} [skip ci]"
                  fail_on_self_push: false

            - name: Create GitHub Release
              uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
              with:
                  tag_name: "v${{ github.event.inputs.version }}"
                  name: "ðŸ”– DeleteBranchCaches v${{ github.event.inputs.version }}"
                  draft: true
                  prerelease: false

            - name: Update Major Release Tag
              run: |
                  MAJOR_VERSION="v$(echo "${{ github.event.inputs.version }}" | cut -d. -f1)"
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
                  git tag -fa "${MAJOR_VERSION}" -m "ðŸ”– Update major version tag to v${{ github.event.inputs.version }}"
                  git push origin "${MAJOR_VERSION}" --force
